apiVersion: v2
name: chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 3.30.0
    condition: enabled.argocd