apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: jenkins-ci
spec:
    destination: 
        namespace: argocd
        server: https://kubernetes.default.svc
    project: ""
    source:
        chart: jenkins-operator
        repoURL: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart